### ISSUE TITLE
Link to documentation is wrong

### ISSUE THREAD

**Issue by PeppeL-G** [tguichaoua/promised-sqlite3#12]
The link to the documentation in the README.md file is wrong:

https://github.com/tguichaoua/promised-sqlite3/blob/befca59abd9f3a927aff4dc69736089c0aa040c9/README.md?plain=1#L61

I'm guessing the link should be:

https://tguichaoua.github.io/promised-sqlite3/

However, I didn't find what I was looking for there neither. After having inserted a new post, I would like to retrieve the id the new post got. The docs says that [run()](https://tguichaoua.github.io/promised-sqlite3/v1/classes/_promiseddatabase_.promiseddatabase.html#run) returns a `RunResult`, but there's no documentation of what a `RunResult` is. But looking at the implementation, I can see it's `this` so I'm guessing I can use `runResult.lastID` to obtain the id the post got. Maybe this can be clarified?

Otherwise this library seem to be precisely what I was looking for. Thank you!

**Comment by tguichaoua** [comment]
The links may be broken since it's a pretty old project. Also I don't have time to maintain this project.
But you can open an PR to fix issues and I will publish a new release.

About the documentation, since this project is build on top of sqlite3, I did not want to re-write the documentation from sqlite3, so I just put a link. Also, if you think the documentation must be clarified, open a PR.

The `RunResult` is describe [here](https://github.com/mapbox/node-sqlite3/wiki/API#databaserunsql-param--callback):

> If execution was successful, the this object will contain two properties named lastID and changes which contain the value of the last inserted row ID and the number of rows affected by this query respectively. Note that lastID only contains valid information when the query was a successfully completed INSERT statement and changes only contains valid information when the query was a successfully completed UPDATE or DELETE statement. In all other cases, the content of these properties is inaccurate and should not be used. The .run() function is the only query method that sets these two values; all other query methods such as .all() or .get() don't retrieve these values.
